# Generated by Django 5.1.1 on 2025-02-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(default=100),
        ),
    ]
