# Generated by Django 5.1.1 on 2025-03-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0006_prescription_prescriptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Medi.appointment'),
            preserve_default=False,
        ),
    ]
