# Generated by Django 5.1.1 on 2025-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0007_prescription_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
