# Generated by Django 5.1.1 on 2025-03-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0008_prescription_remark_prescription_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Medi.appointment'),
        ),
    ]
